@startuml Class

hide members

class Componente <<abstract>>
class Liquido extends Componente
class Solido extends Componente
class Gasoso extends Componente

interface Temperatura <<interface>>
class Frio implements Temperatura
class Quente implements Temperatura
class Ameno implements Temperatura

Componente --> "1" Temperatura : Bridge

@enduml